### ISSUE TITLE
Switch to Contiguous IDL

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-worker#16]
The use of  [Contiguous IDL](https://www.w3.org/respec/guide.html#contiguous-idl) will improve the readability of the spec, and makes spec editing easier.

**Comment by anssiko** [comment]
Started working on this in https://github.com/anssiko/mediacapture-worker/tree/contiguous-idl

This is work-in-progress. I'll craft a PR when done.

**Comment by kakukogou** [comment]
Looks like merging the #19 also close this issue. Since @anssiko mentioned that he is working on the ImageBitmap-extensions part, so I reopen it.

**Comment by anssiko** [comment]
Closed via https://github.com/w3c/mediacapture-worker/pull/19 and https://github.com/w3c/mediacapture-worker/pull/22.
