### ISSUE TITLE
Should there be an onvideomonitor event handler too?

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-worker#18]
The convention is that each event type comes with its own event handler. I think we should add `onvideomonitor`:

```
partial interface DedicatedWorkerGlobalScope {
                attribute EventHandler onvideomonitor;
                attribute EventHandler onvideoprocess;
};
```

This is the usual boilerplate specifications tend to use, adapted to this spec:

> The following are the event handlers (and their corresponding event handler event types) that must be supported, as event handler IDL attributes, by objects implementing the DedicatedWorkerGlobalScope interface:
> 
> | Event handler | Event handler event type |
> | --- | --- |
> | onvideomonitor | videomonitor |
> | onvideoprocess | videoprocess |

**Comment by kakukogou** [comment]
Agree, as long as it is a widely adopted convention.

**Comment by ChiahungTai** [comment]
LGTM. Less confusion. :+1:
