### ISSUE TITLE
The name of enum DataType is too generic

### ISSUE THREAD

**Issue by kakukogou** [w3c/mediacapture-worker#40]
@smaug---- suggested that this enumeration should be called `ChannelPixelLayoutDataType`. The original name `DataType` is just too generic.

**Comment by anssiko** [comment]
Sounds good. The enum name is not exposed to JS, so it should be called something that is meaningful for implementers.

I guess we'll keep the attribute name that is exposed to JS intact as `ChannelPixelLayout.dataType`.
