### ISSUE TITLE
Simplify the ChannelPixelLayout and ImageFormatPixelLayout

### ISSUE THREAD

**Issue by kakukogou** [w3c/mediacapture-worker#41]
@rocallahan suggested that rename the `ImageFormatPixelLayout` to `ImagePixelLayout` because the original one is too redundant. 

@smaug---- suggested using WebIDL dictionary for `ChannelPixelLayout` and then the `Image(Format)PixelLayout` becomes just `sequence<ChannelPixelLayout>`. (maybe using a `typedef`)

**Comment by anssiko** [comment]
LGTM.

One case where using a constructor for `ChannelPixelLayout` might come handy would be to provide some sort of error handling for invalid input per channel. However, I think we're better off doing that on the `ImageFormatPixelLayout` level instead.
