### ISSUE TITLE
Publish First Public Working Draft

### ISSUE THREAD

**Issue by anssiko** [w3c/mediacapture-worker#49]
This is a meta issue to keep us aware of the fact that we should attempt to publish a [First Public Working Draft](https://www.w3.org/2015/Process-20150901/#first-wd) (FPWD) of the spec in the near future, say by the end of June. FPWD is the first step in the formal Recommendation Track, has the following requirements from the W3C Process point of view:
- [ ] must record the group's decision to request advancement.
  - Chairs @stefhak and/or @alvestrand to send Call for Consensus to publish a FPWD to the group's mailing list
- [ ] must obtain Director approval.
  - The Chairs (or Team Contact) sends a transition request to the Domain Lead(s) responsible for the group(s) publishing the document.
- [x] must provide public documentation of all substantive changes to the technical report since the previous publication.
  - (not relevant, since this is the first publication)
- [x] must formally address all issues raised about the document since the previous maturity level.
  - (not relevant, since this is the first publication)
- [ ] must provide public documentation of any Formal Objections.
- [x] should provide public documentation of changes that are not substantive.
  - (not relevant, since this is the first publication)
- [x] should report which, if any, of the Working Group's requirements for this document have changed since the previous step.
  - (not relevant, since this is the first publication)
- [x] should report any changes in dependencies with other groups.
  - (not relevant, since this is the first publication)
- [ ] should provide information about implementations known to the Working Group.

I'll volunteer to fix the Pubrules Checker errors to make the document valid for publication, see:
- [Working Draft produced by spec-generator](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawgit.com%2Fw3c%2Fmediacapture-worker%2Fgh-pages%2Findex.html%3FspecStatus%3DFPWD)
- [Pubrules Checker results](https://labs.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%253A%252F%252Frawgit.com%252Fw3c%252Fmediacapture-worker%252Fgh-pages%252Findex.html%253FspecStatus%253DFPWD&profile=FPWD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004&processDocument=2015)

**Comment by anssiko** [comment]
Fixed Pubrules Checker errors with bc1bf1f84b4fc3a70c76355869d1105957cf6a28.

**Comment by anssiko** [comment]
Fixed issue #30 (with PR #53) that we considered a blocker for the FPWD release.

@ChiahungTai @kakukogou would you like to take a stab at fixing #38 and/or #39 before we attempt to publish?

**Comment by kakukogou** [comment]
@anssiko, thanks for tracking the progress! I will take both #38 and #39.

**Comment by anssiko** [comment]
Thank you @kakukogou! I'll review when you're done.

**Comment by anssiko** [comment]
Closed with https://github.com/w3c/mediacapture-worker/pull/59
